CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TYPE public.jobstatus AS ENUM (
    'queued',
    'processing',
    'done',
    'skipped',
    'not_found',
    'error'
);

ALTER TYPE public.jobstatus OWNER TO dt_admin;

CREATE TABLE public.assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_key CHARACTER VARYING(64),
    asset_name TEXT,
    cmms_asset_id BIGINT,
    dc_asset_id TEXT,
    CONSTRAINT pk_assets PRIMARY KEY (asset_id),
    CONSTRAINT ux_assets_asset_key UNIQUE (asset_key),
    CONSTRAINT ux_assets_cmms_asset_id UNIQUE (cmms_asset_id),
    CONSTRAINT ux_assets_dc_asset_id UNIQUE (dc_asset_id)
);

ALTER TABLE public.assets OWNER TO dt_admin;

CREATE TABLE public.ranges (
    ranges_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    range_ok_upper REAL,
    range_ok_lower REAL,
    range_warn_upper REAL,
    range_warn_lower REAL,
    range_crit_upper REAL,
    range_crit_lower REAL,
    CONSTRAINT pk_ranges PRIMARY KEY (ranges_id)
);

ALTER TABLE public.ranges OWNER TO dt_admin;

CREATE TABLE public.measurement_types (
    measurement_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    measurement_type_key CHARACTER VARYING(64),
    measurement_type_name TEXT,
    unit TEXT NOT NULL,
    unit_name TEXT,
    unit_symbol TEXT,
    CONSTRAINT pk_measurement_types PRIMARY KEY (measurement_type_id),
    CONSTRAINT ux_measurement_types_key UNIQUE (measurement_type_key),
    CONSTRAINT ux_measurement_types_name_unit
        UNIQUE (measurement_type_name, unit_name, unit_symbol)
);

ALTER TABLE public.measurement_types OWNER TO dt_admin;

CREATE TABLE public.failure_types (
    failure_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    failure_type_name TEXT,
    is_preventive BOOLEAN,
    failure_cause_id BIGINT,
    CONSTRAINT pk_failure_types PRIMARY KEY (failure_type_id)
);

ALTER TABLE public.failure_types OWNER TO dt_admin;

CREATE TABLE public.sensor_types (
    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sensor_type_key CHARACTER VARYING(64),
    type_name TEXT NOT NULL,
    max_value REAL,
    min_value REAL,
    measurement_type_id BIGINT NOT NULL,
    accuracy REAL,
    CONSTRAINT pk_sensor_types PRIMARY KEY (type_id),
    CONSTRAINT ux_sensor_types_key UNIQUE (sensor_type_key),
    CONSTRAINT ux_sensor_types_name_measurement_type
        UNIQUE (type_name, measurement_type_id),
    CONSTRAINT fk_sensor_types_measurement_types
        FOREIGN KEY (measurement_type_id)
        REFERENCES public.measurement_types (measurement_type_id)
);

ALTER TABLE public.sensor_types OWNER TO dt_admin;

CREATE TABLE public.asset_failure_types (
    asset_failure_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_id BIGINT NOT NULL,
    failure_type_id BIGINT,
    default_occurrence_probability REAL,
    severity INTEGER,
    asset_failurecause_id BIGINT,
    CONSTRAINT pk_asset_failure_types PRIMARY KEY (asset_failure_type_id),
    CONSTRAINT fk_asset_failure_types_assets
        FOREIGN KEY (asset_id) REFERENCES public.assets (asset_id),
    CONSTRAINT fk_asset_failure_types_failure_types
        FOREIGN KEY (failure_type_id)
        REFERENCES public.failure_types (failure_type_id)
);

ALTER TABLE public.asset_failure_types OWNER TO dt_admin;

CREATE TABLE public.sensors (
    sensor_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sensor_key CHARACTER VARYING(64),
    sensor_name TEXT NOT NULL,
    measurement_frequency REAL,
    ranges_id BIGINT,
    type_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    metric_function_id TEXT,
    CONSTRAINT pk_sensors PRIMARY KEY (sensor_id),
    CONSTRAINT ux_sensors_key UNIQUE (sensor_key),
    CONSTRAINT fk_sensors_ranges
        FOREIGN KEY (ranges_id) REFERENCES public.ranges (ranges_id),
    CONSTRAINT fk_sensors_sensor_types
        FOREIGN KEY (type_id) REFERENCES public.sensor_types (type_id),
    CONSTRAINT fk_sensors_assets
        FOREIGN KEY (asset_id) REFERENCES public.assets (asset_id)
);

ALTER TABLE public.sensors OWNER TO dt_admin;

CREATE TABLE public.measurements (
    measurement_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sensor_id BIGINT NOT NULL,
    "time" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    value REAL NOT NULL,
    CONSTRAINT pk_measurements PRIMARY KEY (measurement_id, "time"),
    CONSTRAINT fk_measurements_sensors
        FOREIGN KEY (sensor_id) REFERENCES public.sensors (sensor_id)
);

SELECT create_hypertable(
    'public.measurements',
    by_range('time'),
    if_not_exists => TRUE
);

ALTER TABLE public.measurements OWNER TO dt_admin;

CREATE TABLE public.datacollector_sync_state (
    sync_name CHARACTER VARYING(100) NOT NULL,
    last_successful_time_to TIMESTAMP WITHOUT TIME ZONE,
    last_metrics_sync_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_datacollector_sync_state PRIMARY KEY (sync_name)
);

ALTER TABLE public.datacollector_sync_state OWNER TO dt_admin;

CREATE TABLE public.etas_betas (
    eta_beta_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    eta_value REAL NOT NULL,
    beta_value REAL NOT NULL,
    asset_failure_type_id BIGINT NOT NULL,
    learning_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_etas_betas PRIMARY KEY (eta_beta_id),
    CONSTRAINT fk_etas_betas_asset_failure_types
        FOREIGN KEY (asset_failure_type_id)
        REFERENCES public.asset_failure_types (asset_failure_type_id)
);

ALTER TABLE public.etas_betas OWNER TO dt_admin;

CREATE TABLE public.asset_worksheet_lists (
    asset_worksheet_list_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_id BIGINT NOT NULL,
    maintenance_end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    source_sys_time TIMESTAMP WITHOUT TIME ZONE,
    asset_failure_type_id BIGINT,
    failure_start_time TIMESTAMP WITHOUT TIME ZONE,
    downtime_in_min BIGINT,
    sys_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_asset_worksheet_lists
        PRIMARY KEY (asset_worksheet_list_id, maintenance_end_date),
    CONSTRAINT fk_asset_worksheet_lists_assets
        FOREIGN KEY (asset_id) REFERENCES public.assets (asset_id),
    CONSTRAINT fk_asset_worksheet_lists_asset_failure_types
        FOREIGN KEY (asset_failure_type_id)
        REFERENCES public.asset_failure_types (asset_failure_type_id)
);

SELECT create_hypertable(
    'public.asset_worksheet_lists',
    by_range('maintenance_end_date'),
    if_not_exists => TRUE
);

ALTER TABLE public.asset_worksheet_lists OWNER TO dt_admin;

CREATE TABLE public.operations_done_lists (
    operations_done_list_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    operation_template_id BIGINT NOT NULL,
    asset_worksheet_list_id BIGINT NOT NULL,
    maintenance_end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_operations_done_lists PRIMARY KEY (operations_done_list_id),
    CONSTRAINT fk_operations_done_lists_asset_worksheet_lists
        FOREIGN KEY (asset_worksheet_list_id, maintenance_end_date)
        REFERENCES public.asset_worksheet_lists (
            asset_worksheet_list_id,
            maintenance_end_date
        )
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

ALTER TABLE public.operations_done_lists OWNER TO dt_admin;

CREATE TABLE public.prediction_jobs (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_hash CHARACTER VARYING(64) NOT NULL,
    payload JSON NOT NULL,
    status public.jobstatus NOT NULL,
    endpoint_type CHARACTER VARYING NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    workorder_id BIGINT NOT NULL,
    CONSTRAINT pk_prediction_jobs PRIMARY KEY (job_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_prediction_jobs_request_hash
    ON public.prediction_jobs (request_hash);

ALTER TABLE public.prediction_jobs OWNER TO dt_admin;

CREATE TABLE public.predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    nowcast_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    forecast_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_predictions PRIMARY KEY (prediction_id),
    CONSTRAINT fk_predictions_assets
        FOREIGN KEY (asset_id) REFERENCES public.assets (asset_id),
    CONSTRAINT fk_predictions_prediction_jobs
        FOREIGN KEY (job_id) REFERENCES public.prediction_jobs (job_id)
);

CREATE INDEX ix_predictions_asset_nowcast_time
    ON public.predictions (asset_id, nowcast_time);

ALTER TABLE public.predictions OWNER TO dt_admin;

CREATE TABLE public.prediction_asset_levels (
    prediction_asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prediction_id BIGINT NOT NULL,
    nowcast_reliability REAL NOT NULL,
    forecast_reliability REAL NOT NULL,
    nowcast_virtual_age REAL NOT NULL,
    forecast_virtual_age REAL NOT NULL,
    CONSTRAINT pk_prediction_asset_levels
        PRIMARY KEY (prediction_asset_id),
    CONSTRAINT ux_prediction_asset_levels_prediction
        UNIQUE (prediction_id),
    CONSTRAINT fk_prediction_asset_levels_predictions
        FOREIGN KEY (prediction_id) REFERENCES public.predictions (prediction_id)
        ON DELETE CASCADE
);

ALTER TABLE public.prediction_asset_levels OWNER TO dt_admin;

CREATE TABLE public.prediction_asset_failure_type_levels (
    prediction_asset_failure_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prediction_id BIGINT NOT NULL,
    asset_failure_type_id BIGINT NOT NULL,
    nowcast_failure_type_probability REAL NOT NULL,
    forecast_failure_type_probability REAL NOT NULL,
    CONSTRAINT pk_prediction_asset_failure_type_levels
        PRIMARY KEY (prediction_asset_failure_id),
    CONSTRAINT ux_prediction_failure_type
        UNIQUE (prediction_id, asset_failure_type_id),
    CONSTRAINT fk_prediction_asset_failure_type_levels_predictions
        FOREIGN KEY (prediction_id) REFERENCES public.predictions (prediction_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_prediction_asset_failure_type_levels_failure_types
        FOREIGN KEY (asset_failure_type_id)
        REFERENCES public.asset_failure_types (asset_failure_type_id)
);

ALTER TABLE public.prediction_asset_failure_type_levels OWNER TO dt_admin;

CREATE TABLE public.sensor_failure_types (
    sensor_failure_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sensor_id BIGINT NOT NULL,
    failure_type_id BIGINT NOT NULL,
    CONSTRAINT pk_sensor_failure_types PRIMARY KEY (sensor_failure_type_id),
    CONSTRAINT ux_sensor_failure_types_sensor_failure
        UNIQUE (sensor_id, failure_type_id),
    CONSTRAINT fk_sensor_failure_types_sensors
        FOREIGN KEY (sensor_id) REFERENCES public.sensors (sensor_id),
    CONSTRAINT fk_sensor_failure_types_failure_types
        FOREIGN KEY (failure_type_id) REFERENCES public.failure_types (failure_type_id)
);

ALTER TABLE public.sensor_failure_types OWNER TO dt_admin;

CREATE TABLE public.sensor_statistics (
    sensor_statistic_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sensor_id BIGINT NOT NULL,
    standard_deviation_value REAL NOT NULL,
    average_value REAL NOT NULL,
    learning_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_sensor_statistics PRIMARY KEY (sensor_statistic_id),
    CONSTRAINT fk_sensor_statistics_sensors
        FOREIGN KEY (sensor_id) REFERENCES public.sensors (sensor_id)
);

ALTER TABLE public.sensor_statistics OWNER TO dt_admin;

CREATE TABLE public.gammas (
    gamma_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    gamma_value REAL NOT NULL,
    sensor_failure_type_id BIGINT NOT NULL,
    contribution REAL NOT NULL,
    learning_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_gammas PRIMARY KEY (gamma_id),
    CONSTRAINT fk_gammas_sensor_failure_types
        FOREIGN KEY (sensor_failure_type_id)
        REFERENCES public.sensor_failure_types (sensor_failure_type_id)
);

ALTER TABLE public.gammas OWNER TO dt_admin;

-- Dashboard, process topology, production tracking and live-data support.
CREATE TABLE public.data_sources (
    data_source_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_key CHARACTER VARYING(64) NOT NULL,
    source_name TEXT NOT NULL,
    source_type CHARACTER VARYING(16) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_data_sources PRIMARY KEY (data_source_id),
    CONSTRAINT ux_data_sources_source_key UNIQUE (source_key),
    CONSTRAINT ck_data_sources_source_type
        CHECK (source_type IN ('physical', 'simulation'))
);

ALTER TABLE public.data_sources OWNER TO dt_admin;

ALTER TABLE public.sensors
    ADD COLUMN chart_aggregation_method CHARACTER VARYING(16)
        NOT NULL DEFAULT 'latest';

ALTER TABLE public.sensors
    ADD CONSTRAINT ck_sensors_chart_aggregation_method
    CHECK (chart_aggregation_method IN ('average', 'latest', 'minimum', 'maximum'));

ALTER TABLE public.measurements
    ADD COLUMN data_source_id BIGINT;

UPDATE public.measurements
SET data_source_id = (
    SELECT data_source_id FROM public.data_sources WHERE source_key = 'real'
)
WHERE data_source_id IS NULL;

ALTER TABLE public.measurements
    ALTER COLUMN data_source_id SET DEFAULT 1,
    ALTER COLUMN data_source_id SET NOT NULL,
    ADD CONSTRAINT fk_measurements_data_sources
        FOREIGN KEY (data_source_id)
        REFERENCES public.data_sources (data_source_id);

CREATE INDEX ix_measurements_sensor_source_time
    ON public.measurements (sensor_id, data_source_id, "time" DESC);

CREATE TABLE public.process_configurations (
    process_configuration_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    configuration_key CHARACTER VARYING(64),
    configuration_name TEXT NOT NULL,
    valid_from TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP WITHOUT TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_process_configurations PRIMARY KEY (process_configuration_id),
    CONSTRAINT ux_process_configurations_key UNIQUE (configuration_key),
    CONSTRAINT ck_process_configurations_valid_range
        CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE UNIQUE INDEX ux_process_configurations_single_active
    ON public.process_configurations (is_active)
    WHERE is_active;

ALTER TABLE public.process_configurations OWNER TO dt_admin;

CREATE TABLE public.process_steps (
    process_step_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    process_step_key CHARACTER VARYING(64),
    process_step_name TEXT NOT NULL,
    processing_time REAL NOT NULL,
    CONSTRAINT pk_process_steps PRIMARY KEY (process_step_id),
    CONSTRAINT ux_process_steps_key UNIQUE (process_step_key),
    CONSTRAINT ck_process_steps_processing_time CHECK (processing_time >= 0)
);

ALTER TABLE public.process_steps OWNER TO dt_admin;

CREATE TABLE public.asset_process_steps (
    asset_process_step_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    process_configuration_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    process_step_id BIGINT NOT NULL,
    CONSTRAINT pk_asset_process_steps PRIMARY KEY (asset_process_step_id),
    CONSTRAINT ux_asset_process_steps_configuration_asset_step
        UNIQUE (process_configuration_id, asset_id, process_step_id),
    CONSTRAINT fk_asset_process_steps_configuration
        FOREIGN KEY (process_configuration_id)
        REFERENCES public.process_configurations (process_configuration_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_asset_process_steps_assets
        FOREIGN KEY (asset_id) REFERENCES public.assets (asset_id),
    CONSTRAINT fk_asset_process_steps_steps
        FOREIGN KEY (process_step_id)
        REFERENCES public.process_steps (process_step_id)
);

ALTER TABLE public.asset_process_steps OWNER TO dt_admin;

CREATE TABLE public.routing (
    routing_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    process_configuration_id BIGINT NOT NULL,
    process_step_id BIGINT NOT NULL,
    next_process_step_id BIGINT NOT NULL,
    CONSTRAINT pk_routing PRIMARY KEY (routing_id),
    CONSTRAINT ux_routing_configuration_edge
        UNIQUE (process_configuration_id, process_step_id, next_process_step_id),
    CONSTRAINT ck_routing_no_self_reference
        CHECK (process_step_id <> next_process_step_id),
    CONSTRAINT fk_routing_configuration
        FOREIGN KEY (process_configuration_id)
        REFERENCES public.process_configurations (process_configuration_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_routing_step
        FOREIGN KEY (process_step_id)
        REFERENCES public.process_steps (process_step_id),
    CONSTRAINT fk_routing_next_step
        FOREIGN KEY (next_process_step_id)
        REFERENCES public.process_steps (process_step_id)
);

ALTER TABLE public.routing OWNER TO dt_admin;

CREATE TABLE public.product_types (
    product_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_type_key CHARACTER VARYING(64),
    product_type_name TEXT NOT NULL,
    max_quantity INTEGER,
    CONSTRAINT pk_product_types PRIMARY KEY (product_type_id),
    CONSTRAINT ux_product_types_key UNIQUE (product_type_key),
    CONSTRAINT ux_product_types_name UNIQUE (product_type_name),
    CONSTRAINT ck_product_types_max_quantity
        CHECK (max_quantity IS NULL OR max_quantity > 0)
);

ALTER TABLE public.product_types OWNER TO dt_admin;

CREATE TABLE public.orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_name TEXT,
    order_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fulfillment_date TIMESTAMP WITHOUT TIME ZONE,
    priority BOOLEAN NOT NULL DEFAULT FALSE,
    status CHARACTER VARYING(16) NOT NULL DEFAULT 'pending',
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT ck_orders_status
        CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled'))
);

ALTER TABLE public.orders OWNER TO dt_admin;

CREATE TABLE public.order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_type_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    requested_quantity INTEGER NOT NULL,
    completed_quantity INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_order_items PRIMARY KEY (order_item_id),
    CONSTRAINT ux_order_items_order_position UNIQUE (order_id, position),
    CONSTRAINT ux_order_items_order_product_type UNIQUE (order_id, product_type_id),
    CONSTRAINT ck_order_items_position CHECK (position > 0),
    CONSTRAINT ck_order_items_requested_quantity CHECK (requested_quantity > 0),
    CONSTRAINT ck_order_items_completed_quantity
        CHECK (
            completed_quantity >= 0
            AND completed_quantity <= requested_quantity
        ),
    CONSTRAINT fk_order_items_orders
        FOREIGN KEY (order_id) REFERENCES public.orders (order_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product_types
        FOREIGN KEY (product_type_id)
        REFERENCES public.product_types (product_type_id)
);

ALTER TABLE public.order_items OWNER TO dt_admin;

CREATE TABLE public.product_instances (
    product_instance_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_item_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL,
    product_serial TEXT,
    status CHARACTER VARYING(16) NOT NULL DEFAULT 'queued',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_product_instances PRIMARY KEY (product_instance_id),
    CONSTRAINT ux_product_instances_item_sequence
        UNIQUE (order_item_id, sequence_number),
    CONSTRAINT ux_product_instances_serial UNIQUE (product_serial),
    CONSTRAINT ck_product_instances_sequence CHECK (sequence_number > 0),
    CONSTRAINT ck_product_instances_status
        CHECK (status IN ('queued', 'assigned', 'in_progress', 'completed', 'cancelled')),
    CONSTRAINT fk_product_instances_order_items
        FOREIGN KEY (order_item_id)
        REFERENCES public.order_items (order_item_id)
        ON DELETE CASCADE
);

ALTER TABLE public.product_instances OWNER TO dt_admin;

CREATE TABLE public.trays (
    tray_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nfc_tag_id TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_trays PRIMARY KEY (tray_id),
    CONSTRAINT ux_trays_nfc_tag_id UNIQUE (nfc_tag_id)
);

ALTER TABLE public.trays OWNER TO dt_admin;

CREATE TABLE public.tray_product_assignments (
    tray_product_assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tray_id BIGINT NOT NULL,
    product_instance_id BIGINT NOT NULL,
    assigned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tray_product_assignments PRIMARY KEY (tray_product_assignment_id),
    CONSTRAINT ck_tray_product_assignments_time_range
        CHECK (released_at IS NULL OR released_at >= assigned_at),
    CONSTRAINT fk_tray_product_assignments_trays
        FOREIGN KEY (tray_id) REFERENCES public.trays (tray_id),
    CONSTRAINT fk_tray_product_assignments_products
        FOREIGN KEY (product_instance_id)
        REFERENCES public.product_instances (product_instance_id)
);

CREATE UNIQUE INDEX ux_tray_product_assignments_active_tray
    ON public.tray_product_assignments (tray_id)
    WHERE released_at IS NULL;

CREATE UNIQUE INDEX ux_tray_product_assignments_active_product
    ON public.tray_product_assignments (product_instance_id)
    WHERE released_at IS NULL;

ALTER TABLE public.tray_product_assignments OWNER TO dt_admin;

CREATE TABLE public.product_tracking_events (
    product_tracking_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_instance_id BIGINT NOT NULL,
    process_step_id BIGINT,
    asset_id BIGINT,
    tray_id BIGINT,
    "time" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    state CHARACTER VARYING(16) NOT NULL,
    CONSTRAINT pk_product_tracking_events PRIMARY KEY (product_tracking_event_id),
    CONSTRAINT ck_product_tracking_events_state
        CHECK (state IN ('arrived', 'departed', 'done')),
    CONSTRAINT fk_product_tracking_events_products
        FOREIGN KEY (product_instance_id)
        REFERENCES public.product_instances (product_instance_id),
    CONSTRAINT fk_product_tracking_events_steps
        FOREIGN KEY (process_step_id)
        REFERENCES public.process_steps (process_step_id),
    CONSTRAINT fk_product_tracking_events_assets
        FOREIGN KEY (asset_id) REFERENCES public.assets (asset_id),
    CONSTRAINT fk_product_tracking_events_trays
        FOREIGN KEY (tray_id) REFERENCES public.trays (tray_id)
);

CREATE INDEX ix_product_tracking_events_product_time
    ON public.product_tracking_events (product_instance_id, "time");

ALTER TABLE public.product_tracking_events OWNER TO dt_admin;

CREATE TABLE public.kpi_definitions (
    kpi_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kpi_name TEXT NOT NULL,
    kpi_unit TEXT NOT NULL,
    value_type CHARACTER VARYING(16) NOT NULL,
    CONSTRAINT pk_kpi_definitions PRIMARY KEY (kpi_id),
    CONSTRAINT ux_kpi_definitions_name UNIQUE (kpi_name),
    CONSTRAINT ck_kpi_definitions_value_type
        CHECK (value_type IN ('int', 'float', 'percent'))
);

ALTER TABLE public.kpi_definitions OWNER TO dt_admin;

CREATE TABLE public.kpi_values (
    kpi_value_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "time" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    kpi_id BIGINT NOT NULL,
    data_source_id BIGINT,
    value REAL NOT NULL,
    CONSTRAINT pk_kpi_values PRIMARY KEY (kpi_value_id, "time"),
    CONSTRAINT fk_kpi_values_definitions
        FOREIGN KEY (kpi_id) REFERENCES public.kpi_definitions (kpi_id),
    CONSTRAINT fk_kpi_values_data_sources
        FOREIGN KEY (data_source_id)
        REFERENCES public.data_sources (data_source_id)
);

SELECT create_hypertable(
    'public.kpi_values',
    by_range('time'),
    if_not_exists => TRUE
);

ALTER TABLE public.kpi_values OWNER TO dt_admin;

CREATE TABLE public.user_types (
    user_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_type_key CHARACTER VARYING(64),
    user_type_name TEXT NOT NULL,
    CONSTRAINT pk_user_types PRIMARY KEY (user_type_id),
    CONSTRAINT ux_user_types_key UNIQUE (user_type_key),
    CONSTRAINT ux_user_types_name UNIQUE (user_type_name)
);

ALTER TABLE public.user_types OWNER TO dt_admin;

CREATE TABLE public.user_type_kpis (
    user_type_id BIGINT NOT NULL,
    kpi_id BIGINT NOT NULL,
    CONSTRAINT pk_user_type_kpis PRIMARY KEY (user_type_id, kpi_id),
    CONSTRAINT fk_user_type_kpis_user_types
        FOREIGN KEY (user_type_id)
        REFERENCES public.user_types (user_type_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_type_kpis_kpis
        FOREIGN KEY (kpi_id)
        REFERENCES public.kpi_definitions (kpi_id)
        ON DELETE CASCADE
);

ALTER TABLE public.user_type_kpis OWNER TO dt_admin;
